version: '3.8'

services:
  php:
    build: .
    container_name: art-gallery-php
    ports:
      - "8081:80"
    volumes:
      - ./agms:/var/www/html
    networks:
      - app-network
    environment:
      - DB_HOST=mysql

  mysql:
    image: mysql:8.0
    container_name: art-gallery-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: agmsdb
      
    ports:
      - "3307:3306"
    volumes:
      - ./SQL File/agmsdb.sql:/docker-entrypoint-initdb.d/agmsdb.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
